apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-http
  namespace: chonkaas-app-py
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: http
spec:
  rules:
  - host: ""
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc
            port:
              number: 5000
      - path: /chonk
        pathType: Prefix
        backend:
          service:
            name: svc
            port:
              number: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-https
  namespace: chonkaas-app-py
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: https
spec:
  rules:
  - host: ""
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc
            port:
              number: 5000
      - path: /chonk
        pathType: Prefix
        backend:
          service:
            name: svc
            port:
              number: 5000